server:
  port: 53001

#################################
## DATASOURCE
#################################

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sys?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: admin
    driverClassName: com.mysql.jdbc.Driver
    initialSize: 1
    maxActive: 30
    minIdle: 5
    maxWaite: 600000
    testOnBorrow: true
    test-while-idle: true


# LOGGING
logging:
  level:
    root: info
    com:
      iyb:
        ak: debug

